name: tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        # - windows-latest
        version:
        - 'v0.8.2'
        - 'nightly'

    steps:
      - uses: actions/checkout@v2

      # Setup nvim
      - uses: notomo/action-setup-nvim-lua@v1
        with:
          luarocks-version: '3.5.0'

      # Install vusted
      - run: luarocks install vusted

      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: ${{matrix.version}}

      - run: make test
        env:
          VUSTED_NVIM: ${{ steps.vim.outputs.executable }}
